<ul>
    <li>Low-voltage electroosmotic pumps fabricated from track-etched polymer membranes, Ceming Wang, Lin Wang, Xiaorui Zhu, Yugang Wang and Jianming Xue, Lab on chip, <b>12</b>, 1710 (2012).</li>
    <li>Drilling Nanopores in Graphene with Cluster Ions: A Molecular Dynamics Study, Shijun Zhao, Li Lang, Jianming Xue, Yugang Wang, Sha Yan, J. Phys. Chem. C, <b>116</b>,11776 (2012).</li>
    <li>A method to tune the ionic current rectification of track-etched nanopores by using surfactant, Lin Wang, Yu Yan, Yanbo Xie, Long Chen, Jianming Xue, Sha Yan, Yugang Wang, Phys. Chem. Chem. Phys. <b>13</b>, 576 (2011).</li>
    <li>Nanofluidic Pulser Based on Polymer Conical Nanopores, Lin Wang, Lixin Sun, Ceming Wang, Long Chen, Liuxuan Cao, Guoqing Hu, Jianming Xue, Yugang Wang, J. Phys. Chem. C, <b>115</b>, 22736 (2011).</li>
    <li>Effect of SiO_2 substrate on the irradiation-assisted manipulation of supported graphene: a molecular dynamics study, Shijun Zhao, Jianming Xue, YugangWang and Sha Yan Nanotechnology <b>23</b>, 285703 (2012).</li>
    <li>Low-voltage electroosmotic pumping using polyethylene terephthalate track-etched membrane, Ceming Wang, Lin Wang and Jianming Xue Nucl. Instr. Mehoths. B. <b>286</b>, 223 (2012).</li>
    <li>Chemical bonding assisted damage production in single-walled carbon nanotubes induced by low energy ions, Shijun Zhao, Jianming Xue, Yugang Wang and Sha Yan, Applied Physics A, <b>108</b>, 313 (2012).</li>
    <li>Nanofluidic Diode Generated by pH Gradient inside Track-etched Conical Nanopore, Lin Wang, Wei Guo, Yanbo Xie, Xingwei Wang, Jianming Xue and Yugang Wang, Inec: 2010 3rd International Nanoelectronics Conference, <b>1</b> 568-569.</li>
    <li>Self-irradiation of thin SiC nanowires with low-energy ions: a molecular dynamics study， Lixin Sun, Chune Lan, Shijun Zhao, Jianming Xue and YugangWang, J. Phys. D: Appl. Phys. <b>45</b>, 135403 (2012).</li>
    <li>Study on the effect of pressure on the properties of intrinsic point defects in monoclinic zirconia: Ab initio calculations Shijun Zhao, Jianming Xue, Yugang Wang and Sha Yan，J. Appl. Phys. <b>111</b>, 043514 (2012).</li>
    <li>Tuning the band gap of bilayer graphene by ion impantation: Insight from computational studies，Shijun Zhao and Jianming Xue. Phys. Rev. B <b>86</b>, 165428 (2012).</li>
</ul>
